### ISSUE TITLE
English docs/paper?

### ISSUE THREAD

**Issue by suy** [hutorny/multimethods#1]
Hello.

Seems that the "doc" directory contains two copies of the same document. Given the different titles, I imagined that maybe the non-English version was uploaded accidentally with the English name. If this is by chance the case, could you share the English version, please?

Otherwise, I'll keep looking at the library through the source and tests.

Thank you very much!

**Comment by hutorny** [comment]
Thank you for reporting this issue. English version has been pushed to the repo

**Comment by suy** [comment]
Thank you! Much appreciated. :-)
